import { Product } from "./types";

export const products: Product[] = [
    {
        id: "1",
        name: "Essential Black Polo",
        type: "polo",
        price: 85,
        originalPrice: 110,
        rating: 4.8,
        reviewCount: 124,
        sizes: [
            { size: "M", inStock: true, stockCount: 12 },
            { size: "L", inStock: true, stockCount: 8 },
            { size: "XL", inStock: false, stockCount: 0 },
            { size: "XXL", inStock: true, stockCount: 5 },
        ],
        colors: [
            { name: "Black", hex: "#000000" },
            { name: "Navy", hex: "#1E3A8A" },
            { name: "White", hex: "#FFFFFF" },
        ],
        description: "Premium cotton polo with perfect fit and luxurious feel.",
        image: "/images/e1.png", // We'll use the generated image
        category: "Polo",
    },
    {
        id: "2",
        name: "Signa Orange Hoodie",
        type: "hoodie",
        price: 125,
        originalPrice: 160,
        rating: 4.9,
        reviewCount: 89,
        sizes: [
            { size: "M", inStock: true },
            { size: "L", inStock: true },
            { size: "XL", inStock: true },
            { size: "XXL", inStock: true },
        ],
        colors: [
            { name: "Orange", hex: "#FF8C00" },
            { name: "Black", hex: "#000000" },
            { name: "Gray", hex: "#6B7280" },
        ],
        description: "Ultra-soft fleece hoodie designed for comfort and style.",
        image: "/images/e2.png",
        category: "Hoodie",
    },
    {
        id: "3",
        name: "Oversized White Tee",
        type: "tshirt",
        price: 65,
        rating: 4.7,
        reviewCount: 203,
        sizes: [
            { size: "M", inStock: true },
            { size: "L", inStock: true },
            { size: "XL", inStock: true },
            { size: "XXL", inStock: false },
        ],
        colors: [
            { name: "White", hex: "#FFFFFF" },
            { name: "Black", hex: "#000000" },
        ],
        description: "Premium heavyweight cotton oversized t-shirt.",
        image: "/images/e3.png",
        category: "T-Shirt",
    },
    {
        id: "4",
        name: "Ribbed Navy Polo",
        type: "polo",
        price: 95,
        rating: 4.6,
        reviewCount: 67,
        sizes: [
            { size: "M", inStock: true },
            { size: "L", inStock: false },
            { size: "XL", inStock: true },
            { size: "XXL", inStock: true },
        ],
        colors: [
            { name: "Navy", hex: "#1E3A8A" },
            { name: "Black", hex: "#000000" },
        ],
        description: "Textured ribbed polo with premium detailing.",
        image: "/images/e4.png",
        category: "Polo",
    },
    {
        id: "5",
        name: "Classic White Hoodie",
        type: "hoodie",
        price: 110,
        rating: 4.5,
        reviewCount: 45,
        sizes: [
            { size: "M", inStock: true },
            { size: "L", inStock: true },
            { size: "XL", inStock: false },
            { size: "XXL", inStock: true },
        ],
        colors: [
            { name: "Gray", hex: "#6B7280" },
            { name: "Black", hex: "#000000" },
        ],
        description: "Timeless gray hoodie with a soft fleece interior.",
        image: "/images/e6.png",
        category: "Hoodie",
    },
    {
        id: "6",
        name: "Relaxed Fit Black Tee",
        type: "tshirt",
        price: 55,
        rating: 4.4,

        reviewCount: 32,
        sizes: [
            { size: "M", inStock: true },
            { size: "L", inStock: true },
            { size: "XL", inStock: false },
            { size: "XXL", inStock: true },
        ],
        colors: [{ name: "Black", hex: "#000000" }],
        description: "Comfortable relaxed fit black t-shirt.",
        image: "/images/e7.png",
        category: "T-Shirt",
    },
    {
        id: "7",
        name: "Striped Navy Polo",
        type: "polo",
        price: 90,
        rating: 4.7,
        reviewCount: 78,
        sizes: [
            { size: "M", inStock: true },
            { size: "L", inStock: true },
            { size: "XL", inStock: true },
            { size: "XXL", inStock: false },
        ],
        colors: [
            { name: "Navy", hex: "#1E3A8A" },
            { name: "White", hex: "#FFFFFF" },
        ],
        description: "Classic striped polo with a modern fit.",
        image: "/images/e8.png",
        category: "Polo",
    },
];

export const getProductById = (id: string) =>
    products.find((product) => product.id === id);
